# .streamlit/secrets.toml

[connection.snowflake]
account = "RJQYFGE-ML27158"
user = "hweinstein"
password = "FinServ2016!"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
